fastq_folder: download
aligned_folder: results/aligned/
output_folder: results
final_bam_folder: results/bqsr
reference: 'analysis/ref/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz'
reference_unpacked: 'analysis/ref/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'
panel_of_normals: 'analysis/GATK_resource_bundle/1000g_pon.hg38.vcf.gz'
af_only_gnomad: 'analysis/GATK_resource_bundle/af-only-gnomad.hg38.vcf.gz'
reference_version: 'GRCh38'
mutect_scatter_by_chromosome: True
final_bam_file_extension: ".merged.dedup.bqsr.bam"
scattered_vcf_folder: results/variant_calls
vcf_file_extension: ".vcf.gz"
metadata_file: "calling_metadata.tsv"
scatter_name_prefix: "chr"
scatter_name_delimiter: "."
scattering_interval_ranges:
  - '1-22'
  - 'X'
  - 'Y'