# config.yaml

bam_list_file: "metadata/BAMs.list"        # File containing one BAM path per line
reference_genome: "analysis/ref/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"    # Path to reference
scatter_mode: "interval"                  # "chromosome" or "interval"
chromosomes: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","X","Y","Y"]
scatter_count: 400                           # For interval scattering (SplitIntervals)

freebayes_params:                           # Additional FreeBayes parameters
  --min-coverage: "20"
  --limit-coverage: "500"
  --use-best-n-alleles: "4"
  --standard-filters: "true"

results_dir: "results/exomes/VCFs/freebayes_germline_joint"
logs_dir: "results/exomes/VCFs/freebayes_germline_joint/logs"
intervals_dir: "analysis/intervals"
final_merged_vcf: "results/exomes/VCFs/freebayes_germline_joint/final_merged.vcf.gz"

# conda environment for FreeBayes
freebayes_env: "freebayes"

# If using the GATK-based scatter:
gatk_env: "gatk"

# For merging VCFs
bcftools_env: "bcftools"